---
- hosts: all
  tasks:
    - name: "Update AWS config"
      file: dest=~/.aws state=directory
    - template:
        src: "templates/aws_config"
        dest: "~/.aws/config"
    - name: "install common dependencies"
      yum: name=git
      become: yes
    - name: "install python dependencies"
      pip: name={{item}}
      with_items:
         - Flask
         - boto3
      become: yes

- hosts: webui
  tasks:
#    - name: "install python dependencies"
#      pip: name={{item}}
#      with_items:
#         - Flask
#         - boto3
#      become: yes
    - name: "synchronize repository"
      git:
        repo: https://github.com/pozdj/upload.git
        dest: ~/imgUploader
        accept_hostkey: true

- hosts: pdf
  vars:
    - os_packages:
        - gcc
        - libjpeg-devel
        - zlib-devel
  tasks:
    - name: "install common dependencies"
      yum: name={{item}}
      with_items: "{{os_packages}}"
      become: yes
    - name: "install python dependencies"
      pip: name={{item}}
      with_items:
         - jinja2
         - xhtml2pdf
      become: yes
    - name: "synchronize repository"
      git:
        repo: https://github.com/pozdj/pdfgen.git
        dest: ~/pdfGenerator
        accept_hostkey: true
